[workspace]
members = ["m6502"]


[package]
name = "nessy"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
m6502 = { path = "m6502" }
smol = "2.0.2"
spin_sleep = "1.3.3"
wgpu = "28.0.0"
winit = "0.30.12"
